[package]
name = "oop_features_gui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oop_features_gui_crate = { path = "../oop_features_gui_crate" }